apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Crash2412/gitops-lab-mini.git
    path: clusters/development
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
